### ISSUE TITLE
WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

### ISSUE THREAD

**Issue by DanRuta** [ModelDepot/tfjs-yolo-tiny#7] opened 2018-04-27 19:39 UTC
Hello,

Great project, I'm having quite some fun with it!

I've been following the demo, and it works great on a pc, but as soon as I try to use it on a phone, the inference doesn't take place due to a WebGL error (seen through remote debugging).

This also happens on the pc, after the page has been running for a couple of minutes, following which, inference no longer works.

Phone error (instant):
![image](https://user-images.githubusercontent.com/12224772/39381262-74ec839c-4a59-11e8-89f3-f3c4c94c3a5a.png)

PC error (after a couple of minutes of running):
![image](https://user-images.githubusercontent.com/12224772/39381673-d0bdd6d4-4a5a-11e8-99f5-c559263971dc.png)

Any ideas?

PC: 7700k, Geforce 1080, Chrome 66.0.3359.117 
Phone: Galaxy Note FE, Chrome 66.0.3359.126

Edit:
Same happens on 7700k + 1050Ti, and on a laptop's 7200U + Intel HD Graphics 620

**Comment by MikeShi42** [comment] 2018-04-28 00:46
Hrmm... I'm not familiar with that error personally, but it seems like it has to do with excessive memory usage. I'd personally open up an issue on the tfjs project as well, if anything it can use a better error message. (Linking this issue would be nice for anyone else that stumbles upon it)

The package currently has a memory leak around some of the tensors. Probably somewhere in this range we need to call more `.dispose()` on the tensors since they're outside of a `tidy`. https://github.com/ModelDepot/tfjs-yolo-tiny/blob/master/src/index.js#L57-L67

I'm a bit tight on time right now so I might not be able to get around to this until next week. I know that the original poster of #4 suggested he might be working on cleaning up the memory leaks. I know the bug might be annoying to reproduce but I'd suggest just throwing a `dispose` on some of the Tensors in the above lines and seeing if that delays/stops the error from popping up.

**Comment by michaelvogt** [comment] 2018-05-02 03:23
I see the same problem with my Pixel 2 on Chrome 66.0, but all seems to work (slowly) on Firefox 60.0 (haven't checked other versions)

**Comment by MikeShi42** [comment] 2018-05-04 01:23
@michaelvogt Have you tried out cleaning up some of the tensor memory usage (from my last comment)? If it is I'll try to get in a fix (or feel free to PR)

**Comment by michaelvogt** [comment] 2018-05-04 01:29
@MikeShi42 Sorry, I didn't. I had a quick look at the code, but haven't had enough time to work on it.

**Comment by MikeShi42** [comment] 2018-05-04 01:48
@michaelvogt no worries :) I personally haven't been able to repro this yet so it's a bit tricky for me to fix

**Comment by DanRuta** [comment] 2018-05-04 10:20
@MikeShi42 I tried cleaning up whatever tensors I could find, but to no avail. I did notice the GPU memory growing steadily with each inference, so that's probably it. It happens on a different project also, so I think it may indeed be an issue with tfjs itself.

I saw a couple of issues mentioning WebGL issues, so I think they're aware.

For the record, this is the increasing memory usage when running the live demo on my laptop. Once it gets full, the error is thrown.

![image](https://user-images.githubusercontent.com/12224772/39623121-87c6cc9c-4f8c-11e8-9a94-56af6c6611a1.png)

**Comment by bchiu** [comment] 2018-06-13 14:52
the memory leak is fixed by wrapping the code inside yolohead, filterboxes, boxestocorners with tf.tidy. additionally, break out any chained functions into individual vars so they can be referenced and call dispose() on all of them. console.log(tf.memory().numTensors) will let you know if any tensors aren't being cleaned up after each frame. i'd submit a pr, but i've already rewrote my code as a web component.

**Comment by RadEdje** [comment] 2018-10-20 15:05
having similar issues. My tensors are all wrapped in tf.tidy. I've trained a model to detect fracture types by using the computers web camera to look at images. This works on both tf.js version 12 and the latest one at 13. It has around 105 shards when the model is converted for tf.js use.

However, I trained the model to read CT scans using the video camera. With tf.js version 12, the analysis is slow but still runs. With tf.js ver 13, it hangs completely and throws the error:

"WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost"

The model for reading CT has even fewer shards than the one for the X-ray but it hangs with tf.js version 13. Seems tf.js ver 12 handles memory leaks better since the model doesn't hang on that version? Or am I missing something? Is there a new api to handle memory leaks in version 13 I should use besides tf.tidy? Thanks again.

**Comment by MikeShi42** [comment] 2018-10-20 20:34
Hello everyone! Just wanted to give an update, I'll be pushing out a commit shortly that should eliminate all memory leaks. calling `tf.memory()` still has increasing tensor counts (but 10x slower) but memory usage is steady so it should be good for everyone running into memory issues. Will most likely be pushed on a new major version since it uses tf's new NMS function.

**Comment by MikeShi42** [comment] 2018-10-20 21:54
Pushed `1.0.1` to NPM. Relevant commit if anyone's interested: https://github.com/ModelDepot/tfjs-yolo-tiny/commit/ce987fa300226b6145b0533c60b6db2c76eb12c5

Closing out this issue for now, feel free to open a new one if there's still some issues.

**Closed as completed by MikeShi42** 2018-10-20 21:54 UTC
